app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path('fetch_fee_payments/', views.fetch_fee_payments, name='fetch_fee_payments'),


    # customer urls 
    path("add-customer/", views.add_customer, name="add-customer"),
    path("edit-customer/<int:customer_id>/", views.edit_customer, name="edit-customer"),
    path("view-customer/<int:customer_id>/", views.view_customer, name="view-customer"),
    path("delete-customer/<int:customer_id>/", views.delete_customer, name="delete-customer"),
    path("list-of-customers/", views.list_of_customers, name="list-of-customers"),
    # path("search-customer/", views.search_customer, name="search-customer"),
    path('search_customers/', views.search_customers, name='search_customers'),

    # company urls 
    path("add-company/", views.add_company, name="add-company"),
    path("edit-company/<int:company_id>/", views.edit_company, name="edit-company"),
    path("view-company/<int:company_id>/", views.view_company, name="view-company"),
    path("delete-company/<int:company_id>/", views.delete_company, name="delete-company"),
    path("list-of-companies/", views.list_of_companies, name="list-of-companies"),
    path('search_companies/', views.search_companies, name='search_companies'),

    # job urls 
    path("add-job/", views.add_job, name="add-job"),
    path("edit-job/<int:job_id>/", views.edit_job, name="edit-job"),
    path("view-job/<int:job_id>/", views.view_job, name="view-job"),
    path("delete-job/<int:job_id>/", views.delete_job, name="delete-job"),
    path("list-of-jobs/", views.list_of_jobs, name="list-of-jobs"),
    path('search_placements/', views.search_placements, name='search_placements'),

    # jobbcategory urls 
    path("add-jobcategory/", views.add_jobposition, name="add-jobcategory"),
    path("edit-jobcategory/<int:jobcategory_id>/", views.edit_jobposition, name="edit-jobcategory"),
    path("view-jobcategory/<int:jobcategory_id>/", views.view_jobposition, name="view-jobcategory"),
    path("delete-jobcategory/<int:jobcategory_id>/", views.delete_jobposition, name="delete-jobcategory"),
    path("list-of-jobcategories/", views.list_of_jobpositions, name="list-of-jobcategories"),
    path("list-of-jobcategories/<int:jobcategory_id>", views.list_of_jobpositions, name="list-of-jobcategories"),
    # path("search-jobcategory/", views.search_jobposition, name="search-jobcategory"),

    # fee urls 
    path("add-fee/", views.add_fee, name="add-fee"),
    path("edit-fee/<int:fee_id>/", views.edit_fee, name="edit-fee"),
    path("view-fee/<int:fee_id>/", views.view_fee, name="view-fee"),
    path("delete-fee/<int:fee_id>/", views.delete_fee, name="delete-fee"),
    path("list-of-fees/", views.list_of_fees, name="list-of-fees"),
    path('preview_receipt/<int:fee_id>/', views.preview_receipt, name='preview_receipt'),
    path('generate_receipt/<int:fee_id>/', views.generate_receipt, name='generate_receipt'),



    # placement urls 
    path("add-placement/", views.add_placement, name="add-placement"),
    path("edit-placement/<int:placement_id>/", views.edit_placement, name="edit-placement"),
    path("view-placement/<int:placement_id>/", views.view_placement, name="view-placement"),
    path("delete-placement/<int:placement_id>/", views.delete_placement, name="delete-placement"),
    path("list-of-placements/", views.list_of_placements, name="list-of-placements"),
    # path("search-placement/", views.search_placement, name="search-placement"),

    # consultation urls 
    path("add-consultation/", views.add_consultation, name="add-consultation"),
    path("view-consultation/<int:consultation_id>/", views.view_consultation, name="view-consultation"),
    path("list-of-consultations/", views.list_of_consultations, name="list-of-consultations"),
    # path("search-placement/", views.search_placement, name="search-placement"),

    # settings urls 
    path("roles/", views.roles, name="roles"),
    path("company-settings/", views.company_settings, name="company-settings"),
    path("edit-settings/<int:id>", views.edit_settings, name="edit-settings"),
    path("my-profile/",views.my_profile, name="my-profile"),

    # expenses urls 
    path("add-expense/", views.add_expense, name="add-expense"),
    path("list-of-expenses/", views.list_of_expenses, name="list-of-expenses"),
    path("list-of-expenses-for-all-users/", views.list_of_expenses_of_all_users, name="list-of-expenses-for-all-users"),
    path("edit-expense/<int:expense_id>/", views.edit_expense, name="edit-expense"),
    path("delete-expense/<int:expense_id>/", views.delete_expense, name="delete-expense"),

    # reports views
    path("reports/<str:time_frame>/", views.reports, name="reports"),
    path('reports/<str:time_frame>/export/<str:export_type>/', views.reports, name='export_report'),
]

moto_consults/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from authentication.views import login_view, CustomLogoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", login_view, name="login"), 
    path("app/", include("app.urls")),
    path('app/', include('authentication.urls')),
    path("logout/", CustomLogoutView.as_view(next_page="/"), name="logout"),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)

        # Ensure a role is provided or set a default role
        if 'role' not in extra_fields or extra_fields['role'] is None:
            default_role = "user"
            extra_fields['role'] = default_role

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        # Set the role for superusers to 'admin'
        default_admin_role = "admin"
        extra_fields['role'] = default_admin_role

        return self.create_user(email, password, **extra_fields)
    


class CustomUser(AbstractBaseUser, PermissionsMixin):
    ROLE_CHOICES = (
        ("staff", "User Staff"),
        ("accountant", "User Accountant"),
        ("admin", "User Admin"),
    )
    email = models.EmailField(unique=True)
    firstname = models.CharField(max_length=30)
    othernames = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=64, null=True)
    pass_port_photo = models.ImageField(upload_to="user_images/", null=True)
    role = models.CharField(max_length=254, default="staff", choices=ROLE_CHOICES)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname', 'othernames']

    full_name = f"{firstname} {othernames}"

    def __str__(self):
        return self.email

app/forms.py
from django import forms
from . import models


class CustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = "__all__"

        widgets = {
            "firstname": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "othernames": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phonenumber_1": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phonenumber_2": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control",
            }),
            "passport_photo": forms.ClearableFileInput(attrs={'accept': 'image/*', 'class': 'form-control'}),
            "file_upload": forms.FileInput(attrs={
                "class": "form-control",
            }),
            "remarks": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }


class EditCustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = "__all__"

        widgets = {
            "firstname": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "othernames": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phonenumber_1": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phonenumber_2": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control",
            }),
            "passport_photo": forms.ClearableFileInput(attrs={'accept': 'image/*', 'class': 'form-control'}),
            "file_upload": forms.FileInput(attrs={
                "class": "form-control",
            }),
            "remarks": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }


class CompanySearchForm(forms.Form):
    first_name = forms.CharField(required=False, label='First Name')
    last_name = forms.CharField(required=False, label='Last Name')
    email = forms.EmailField(required=False, label='Email')




# FORMS FOR COMPANY START 


class CompanyForm(forms.ModelForm):
    class Meta:
        model = models.EmployerCompany
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phone_number": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phone_number2": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control",
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }
        


class EditCompanyForm(forms.ModelForm):
    class Meta:
        model = models.EmployerCompany
        fields = "__all__"

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "phone_number": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control",
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }



# FORMS FOR COMPANY END 



# FORMS FOR JOB START 


class JobForm(forms.ModelForm):
    class Meta:
        model = models.Job
        fields = "__all__"

        widgets = {
            "job_title": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "job_position": forms.Select(attrs={
                "class": "form-control",
            }),
            "job_field": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "job_company": forms.Select(attrs={
                "class": "form-control",
            }),
            "job_description": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }


class EditJobForm(forms.ModelForm):
    class Meta:
        model = models.Job
        fields = "__all__"

        widgets = {
            "job_title": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "job_position": forms.Select(attrs={
                "class": "form-control",
            }),
            "job_field": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "job_company": forms.Select(attrs={
                "class": "form-control",
            }),
            "job_description": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }


# FORMS FOR JOB END 



# FORMS FOR JOB POSITIONS

class JobpositionForm(forms.ModelForm):
    class Meta:
        model = models.JobPosition
        fields = "__all__"

        widgets = {
            "job_position": forms.TextInput(attrs={
                "class": "form-control"
            })
        }


class EditJobpositionForm(forms.ModelForm):
    class Meta:
        model = models.JobPosition
        fields = "__all__"

        widgets = {
            "job_position": forms.TextInput(attrs={
                "class": "form-control",
            })
        }

# END FOR JOB POSITIONS FORMS 



# FORMS FOR FEES

class FeeForm(forms.ModelForm):
    class Meta:
        model = models.FeesPayment
        fields = "__all__"


class EditFeeForm(forms.ModelForm):
    class Meta:
        model = models.FeesPayment
        fields = "__all__"

        widgets = {
            "customer": forms.Select(attrs={
                "class": "form-control",
            }),
            "fee_type": forms.Select(attrs={
                "class": "form-control",
            }),
            "amount": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "payment_status": forms.Select(attrs={
                "class": "form-control",
            }),
        }

# END FOR FEES FORMS 



# FORMS FOR PLACEMENTS

class PlacementForm(forms.ModelForm):
    class Meta:
        model = models.RecruitmentProcess
        fields = "__all__"
        widgets = {
            "customer": forms.Select(attrs={
                "class": "form-control"
            }),
            "job": forms.Select(attrs={
                "class": "form-control",
            }),
            "status": forms.Select(attrs={
                "class": "form-control",
            }),
            "expected_salary": forms.NumberInput(attrs={
                "class": "form-control",
            }),
            "company": forms.Select(attrs={
                "class": "form-control"
            })
        }


class EditPlacementForm(forms.ModelForm):
    class Meta:
        model = models.RecruitmentProcess
        fields = "__all__"

        widgets = {
            "customer": forms.Select(attrs={
                "class": "form-control",
            }),
            "job": forms.Select(attrs={
                "class": "form-control",
            }),
            "status": forms.Select(attrs={
                "class": "form-control",
            }),
            "expected_salary": forms.NumberInput(attrs={
                "class": "form-control",
            }),
        }

# END FOR PLACEMMENTS FORMS 



# FORMS FOR CONSULTATIONS

class ConsultationForm(forms.ModelForm):
    class Meta:
        model = models.Consultation
        fields = "__all__"

        widgets = {
            "customer": forms.Select(attrs={
                "class": "form-control",
            }),
            "consultation_fee": forms.NumberInput(attrs={
                "class": "form-control",
            }),
        }


# END FOR CONSULTATION FORMS 


class CompanySettingsForm(forms.ModelForm):
    class Meta:
        model = models.CompanySettings
        fields = ['name', 'email', 'logo', 'favicon', 'address', 'phone_number', "phonenumber_2"]
        widgets = {
            'logo': forms.ClearableFileInput(attrs={'accept': 'image/*', 'class': 'form-control'}),
            'favicon': forms.ClearableFileInput(attrs={'accept': 'image/x-icon,image/vnd.microsoft.icon', 'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'phonenumber_2': forms.TextInput(attrs={'class': 'form-control'}),
        }




# FORMS FOR REGISTRATION FEES

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = models.RegistrationFees
        fields = "__all__"

        widgets = {
            "fees_amount": forms.NumberInput(attrs={
                "class": "form-control",
            })
        }


# END FOR REGISTRATION FORMS 


# FORMS FOR REGISTRATION

class ConnectionFeesForm(forms.ModelForm):
    class Meta:
        model = models.ConnectionFees
        fields = "__all__"

        widgets = {
            "percentage": forms.NumberInput(attrs={
                "class": "form-control",
            })
        }


# END FOR REGISTRATION FORMS 


# FORMS FOR CONSULTATION

class ConsultationFeesForm(forms.ModelForm):

templates/add_consultation.html
{% extends "base.html" %}

{% load static %}

{% block title %}Muto consults | Add consultation{% endblock title %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}
<div>

    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Muto Consults</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Adding a new consultation instance</a></li>
                </ol>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-xl-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">New consultation instance</h4>
                        </div>
                        <div class="card-body">
                            <div class="basic-form">

                                <!-- form for adding a new job  -->
                                <form id="companyForm" method="post" action="">

                                    {% csrf_token %}
                                    {{ form.as_p }}

                                    <div class="mb-3"><button type="submit" class="btn btn-primary mb-2">Save
                                            consultation instance</button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
        <div id="message"></div>
    </div>
</div>
{% endblock content %}

templates/add_fee copy.html
{% extends "base.html" %}

{% load static %}

{% block title %}{% endblock title %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}
<div>
    {% comment %} <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save customer</button>
    </form> {% endcomment %}

    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Form</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Element</a></li>
                </ol>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-xl-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Input Style</h4>
                        </div>
                        <div class="card-body">
                            <div class="basic-form">

                                <!-- form for adding a new customer  -->
                                <form id="customerForm" method="post" enctype="multipart/form-data">

                                    {% csrf_token %}
                                    <div class="mb-3 col-md-12">
                                        <label for="id_firstname" class="form-label">First Name:</label><span
                                            class="text-danger">*</span>
                                        <input type="text" name="firstname" maxlength="100" required id="id_firstname" required
                                            class="form-control" placeholder="Talemwa">
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_othernames" class="form-label">Other Names:</label>
                                        <input type="text" name="othernames" maxlength="100" required id="id_othernames" class="form-control"
                                            placeholder="Eria Jackson">
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_phonenumber_1" class="form-label">Phonenumber 1:</label>
                                        <input type="text" name="phonenumber_1" maxlength="15" required id="id_phonenumber_1" class="form-control" name="phonenumber_1" required>
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_phonenumber_2" class="form-label">Phonenumber 2:</label>
                                        <input type="text" name="phonenumber_2" maxlength="15" id="id_phonenumber_2"
                                            class="form-control" placeholder="0771445200">
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_email" class="form-label">Email:</label>
                                        <input type="email" name="email" maxlength="254" id="id_email" class="form-control"
                                            placeholder="example@gmail.com">
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_address" class="form-label">Address:</label>
                                        <input class="form-control" placeholder="Arua" type="text" name="address" maxlength="64" required id="id_address">
                                    </div>

                                    <div>
                                        <label for="id_passport_photo" class="form-label">Passport photo:</label>
                                    </div>
                                    <div class="form-file mb-3 col-md-12">
                                        <input type="file" name="passport_photo" accept="image/*" id="id_passport_photo" class="form-file-input form-control">
                                    </div>


                                    <div>
                                        <label for="id_file_upload" class="form-label">File upload (CV):</label>
                                    </div>
                                    <div class="form-file mb-3 col-md-12">
                                        <input type="file" name="file_upload" id="id_file_upload"
                                            class="form-file-input form-control">
                                    </div>

                                    <div class="mb-3">
                                        <label for="id_remarks" class="form-label">Remarks:</label>
                                        <textarea id="id_remarks" name="remarks" class="form-control"
                                            rows="4"></textarea>
                                    </div>

                                    <div><button type="submit" class="btn btn-primary mb-2">Save customer</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
        <div id="message"></div>
    </div>
</div>
{% endblock content %}

templates/add_job.html
{% extends "base.html" %}

{% load static %}

{% block title %}{% endblock title %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}
<div>
    {% comment %} <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save customer</button>
    </form> {% endcomment %}

    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Form</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Element</a></li>
                </ol>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-xl-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Input Style</h4>
                        </div>
                        <div class="card-body">
                            <div class="basic-form">

                                <!-- form for adding a new job  -->
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="form_name" value="add_job_form">
                                    {{add_job_form.as_p}}
                                    <div><button type="submit" class="btn btn-primary mb-2">Add
                                            job</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
        <div id="message"></div>
    </div>
</div>
{% endblock content %}

templates/edit_customer.html
{% extends "base.html" %}

{% load static %}

{% block title %}Muto Consults | Edit Customer{% endblock title %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}
<div>

    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Form</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Element</a></li>
                </ol>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-xl-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Input Style</h4>
                        </div>
                        <div class="card-body">
                            <div class="basic-form">

                                <!-- form for editing a customer  -->
                                <form id="customerForm" method="post" enctype="multipart/form-data">

                                    {% csrf_token %}
                                    {{form.as_p}}
                                    <!-- <div class="mb-3 col-md-12">
                                        <label for="id_firstname" class="form-label">First Name:</label><span
                                            class="text-danger">*</span>
                                        {{form.firstname}}
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_othernames" class="form-label">Other Names:</label>
                                        {{form.othernames}}
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_phonenumber_1" class="form-label">Phonenumber 1:</label>
                                        {{form.phonenumber_1}}
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_phonenumber_2" class="form-label">Phonenumber 2:</label>
                                        {{form.phonenumber_2}}
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_email" class="form-label">Email:</label>
                                        {{form.email}}
                                    </div>

                                    <div class="mb-3 col-md-12">
                                        <label for="id_address" class="form-label">Address:</label>
                                        {{form.address}}
                                    </div>

                                    <div>
                                        <label for="id_passport_photo" class="form-label">Passport photo:</label>
                                    </div>
                                    <div class="form-file mb-3 col-md-12">
                                        {{form.passport_photo}}
                                    </div>


                                    <div>
                                        <label for="id_file_upload" class="form-label">File upload (CV):</label>
                                    </div>
                                    <div class="form-file mb-3 col-md-12">
                                        {{form.file_upload}}
                                    </div>

                                    <div class="mb-3">
                                        <label for="id_remarks" class="form-label">Remarks:</label>
                                        {{form.remarks}}
                                    </div> -->

                                    <div><button type="submit" class="btn btn-primary mb-2">Save customer
                                            details</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
        <div id="message"></div>
    </div>
</div>
{% endblock content %}

templates/signup.html
<!DOCTYPE html>
<html>

<head>
    <title>Sign Up</title>
</head>

<body>
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</body>

</html>